### ISSUE TITLE
In case of reconnection, the watcher sometimes will be not work

### ISSUE THREAD

**Issue by lzs123** [microsoft/etcd3#114]
the stream will receive a WatchResponse with created = true and canceled = true and a cancel_reason "rpc error: code = PermissionDenied desc = etcdserver: permission denied". i find out the reason after review the source code. 
![image](https://user-images.githubusercontent.com/24785694/68845047-c2a44d80-0705-11ea-90f2-4e956e8a0a0a.png)  in this case will only trigger the function "this.queue.handleCreate"

**Comment by zyf0330** [comment]
So in this case, watcher chooses to throw error but not keep re-watch?

**Comment by connor4312** [comment]
Correct. Trying to re-watch on an authentication error is not useful.
