### ISSUE TITLE
Getting user's roles is slow

### ISSUE THREAD

**Issue by gtamas** [microsoft/etcd3#122]
@connor4312 

I have this in the code:

`const roles = await this.client.user('someuser').roles();`

this.client is an Etcd3 client. This operation runs very slowly somehow. It takes 3-4 secs, while all other API ops seem to be blazing fast (almost instant). Is this normal?

Why does this take so long? Is there any way to improve the performance?

**Comment by gtamas** [comment]
Btw: I'm using a default ETCD running on localhost, so it's not the slow network.

**Comment by connor4312** [comment]
Please open an issue on etcd if you continue to see this. We don't do much here, we only wrap the APIs it provides.
