### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by stringang** [microsoft/etcd3#125]
I found that the master branch commit record has elevated the `grpc` dependency to `grpc-js`. no new version has been released. 

npm still uses the `grpc` dependency when installing `etcd3`.

the installation of `grpc` requires `node-gyp` compilation, which often fails.

can we release a new version?

Looking forward. Thanks.

**Comment by connor4312** [comment]
I am planning to release the new version this weekend after addressing #121

**Comment by tlhunter** [comment]
I'm currently writing an O'Reilly book, Distributed Node.js, and the timing of this couldn't have been better! `grpc` compatibility between Node.js releases is pretty bad and I'm having to rewrite examples from a couple months ago that is already outdated. `grpc-js` makes things much smoother.

**Comment by connor4312** [comment]
That's clever marketing, now I will have to buy your book 😄 

1.0.0 is out. Let me know if you hit any issues!
