### ISSUE TITLE
Type error because of wrong cockatiel version

### ISSUE THREAD

**Issue by SunshowerC** [microsoft/etcd3#128]
run and got error: 

> node_modules/etcd3/lib/connection-pool.d.ts:14:37 - error TS2344: Type 'unknown' does not satisfy the constraint  'IDefaultPolicyContext'.
> 
> `14     readonly faultHandling: IPolicy<unknown>;`
>  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;  ~~~~~~~

![image](https://user-images.githubusercontent.com/13402013/87292534-88f54200-c533-11ea-8e27-4e74a2a72b37.png)

found `etcd3@1.0.1` is compatible with type definitions of  `cockatiel@1.1.0` .

force install `cockatiel@1.0.0` would fix the problem.

**Comment by jeffrson** [comment]
Thanks @SunshowerC for the workaround recommendation!

But what about a real fix?

**Comment by HelloKevinTian** [comment]
same issue.
Waiting for the fix.
