### ISSUE TITLE
Best way to `getAll(keys)`?

### ISSUE THREAD

**Issue by icetbr** [microsoft/etcd3#173]
I use etcd to store configurations, and I find it useful to load them all in the beginning of the application.

I want to load multiple values in a way that `from` becomes `to`:
```js
const from = {
    X: '/a/b/x',
    Y: '/a/b/y',
    ...
}

const to = {
    X: 'value1',
    Y: 14,
    ...
}
```

What's the best approach? Transactions or a `getAll().prefix(x).prefix(y)...`? Would you find this useful enough to include in the library?

**Comment by connor4312** [comment]
I don't think that's something I would include in the library, and mostly up to you whether you do N lookups for every key or getAll() with a prefix and apply them to the object. Depends on how your keys and database are laid out.
