### ISSUE TITLE
Deadlock when EtcdInvalidAuthTokenError

### ISSUE THREAD

**Issue by wchrt** [microsoft/etcd3#177]
When exec throw a 'EtcdInvalidAuthTokenError' result, It will try exec algin. 
'CircuitBreaker' is waitting first exec ended for Close,  And second exec is waitting 'CircuitBreaker' Close.
Now a deadlock is here, any exec will waiting for the deadlock

**Comment by wchrt** [comment]
I had fixed it as pull requests: [https://github.com/microsoft/etcd3/pull/178](url)

**Comment by connor4312** [comment]
Fixed in the linked PR
