### ISSUE TITLE
pkg was pack success,  but crash in use pack file, error for rpc.proto file path

### ISSUE THREAD

**Issue by HseYang** [microsoft/etcd3#179]
pkg was pack success,  but crash in use pack file, error for rpc.proto file path

![image](https://user-images.githubusercontent.com/33883616/220283001-a47b94a2-17de-476c-848a-accec2d9f633.png)

I can try adding the package to my assets in the pkg config in package.json,

    "assets": [
        ...,
      "node_modules/etcd3/**/*",
      "node_modules/etcd3/**/*.proto",
      "node_modules/etcd3/proto/rpc.proto"
    ]

but same error.

**Comment by connor4312** [comment]
Not clear what the problem is. This module depends on loading the `.proto` files at runtime. You have to make sure those are accessible.
