### ISSUE TITLE
Updates to the repository and fixes but no release

### ISSUE THREAD

**Issue by Kunamatata** [microsoft/etcd3#192]
@connor4312 is it intended that there have not been any releases but there have been commits and fixes in the repository?

**Comment by connor4312** [comment]
Version 1.1.2 contains all commits excluding a documentation change, see the commit log: https://github.com/microsoft/etcd3/commits/master

**Comment by Kunamatata** [comment]
Ah thanks for pointing that out. I saw that the `github` (https://github.com/microsoft/etcd3/releases) releases were lagging but the npm package is at `1.1.2` thanks @connor4312

**Comment by connor4312** [comment]
Gotcha, I made 1.1.1 and 1.1.2 "releases"
