### ISSUE TITLE
Getting error when tried with tls

### ISSUE THREAD

**Issue by stadicshock** [microsoft/etcd3#49]
Getting below error when tried with tls.
```
E1108 12:08:41.067409000 140736133522368 ssl_transport_security.c:177] ssl_info_callback: error occured.

E1108 12:08:41.087651000 140736133522368 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.
(node:17954) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Connect Failed
(node:17954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and in etcdserver i'm getting this error for same request 
```
etcdmain: rejected connection from "127.0.0.1:60846" (tls: no cipher suite supported by both client and server) 
```
Same certs/keys worked fine when I tried with golang library  https://github.com/coreos/etcd/tree/master/clientv3

Any help would be appreciated
thanks in advance

**Comment by satishjhanwer** [comment]
I am having a similar issue. Please let me know if you have figure out the solution for this issue.

**Comment by connor4312** [comment]
We've updated to the latest, new grpc library; this is hopefully fixed for you there. If not, please open an issue on the grpc repo here -- I don't think there's much this library control about TLS! https://github.com/grpc/grpc-node
