### ISSUE TITLE
watcher can't reconnect after disconnection

### ISSUE THREAD

**Issue by MarcCaesars** [microsoft/etcd3#78]
etcd version: 3.3.5
etcd3: 0.2.11

Server log: etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")

How can I fix that bug?

I want to reconnect correctly to etcd cluster, but can't reconnect.

And watcher can't get any event from cluster.

**Comment by zyf0330** [comment]
I meet this too. I choose to recreate etcd instance.

**Comment by zyf0330** [comment]
Maybe it is related to issue #114 .

**Comment by connor4312** [comment]
This sounds like #114 indeed. In that case the watch request would fail but we just keep the connection open forever, thinking that it worked. Closing unless there are reports of repros once that's fixed.
